FROM rogargon/angular-e2e:latest

ADD . /usr/src/skycoin-explorer

WORKDIR /usr/src/skycoin-explorer

RUN npm install && \
    sh -c "sed -i 's/127.0.0.1/explorer/g' protractor-blockchain-180.conf.js"

CMD ["npm", "run", "e2e-blockchain-180"]
